# Generated by Django 2.2 on 2020-05-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='uname',
            new_name='username',
        ),
    ]
